services:
  - type: web
    name: Engineering-Patent-App
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheck:
      path: /health
      initialDelaySeconds: 45 
    envVars:
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.12" # Using a stable Python version
      - key: PORT
        value: "8000"